# Generated by Django 2.0.2 on 2018-05-02 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180501_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 19, 21, 15, 290180, tzinfo=utc)),
        ),
    ]
